"""Portfolio add: Current value

Revision ID: 5f5fac132ce5
Revises: 4a338fa17f30
Create Date: 2025-01-08 12:34:40.213196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5fac132ce5'
down_revision = '4a338fa17f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_value', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('current_value')

    # ### end Alembic commands ###
